[theme]
backgroundColor = "#170352"  # Màu nền chính
secondaryBackgroundColor = "#02490f" # Màu nền của sidebar
primaryColor = "#c2000a"  # Màu chính (nút, highlight)
textColor = "#ede91c"     # Màu chữ
#ffaf53